site_name: HammerTime Documentation
repo_url: https://github.com/delvelabs/hammertime/
pages:
- 'getting_started.md'
- 'create_heuristics.md'
- 'proxy.md'
- 'reference.md'
- 'engine.md'
- 'heuristics.md'