site_name: HammerTime Documentation
site_url: http://127.0.0.1:8000/docs/hammertime
repo_url: https://github.com/delvelabs/hammertime/
pages:
- 'getting_started.md'
- 'create_heuristics.md'
- 'proxy.md'
- 'reference.md'
- 'engine.md'
- 'heuristics.md'